spring:
  application:
    name: raising-stocks
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost